version: "3.8"

services:
  backend:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      USERNAME: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: ${HOST}
      PORT: ${PORT}
      DBNAME: ${DBNAME}
    volumes:
      - .:/app
    restart: on-failure

  postgres:
    image: postgres:17.4
    container_name: test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U", "test" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: