version: "3.12"
services:
  backend:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://test:test@postgres:5432/test
  postgres:
    image: postgres:17.4
    container_name: test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
