version: "3.12"
services:
  postgres:
    image: postgres:17.4
    container_name: test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
