version: "3.8"

services:
  backend:
    build: .
    container_name: api
    ports:
      - "7777:7777"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
    restart: on-failure

  postgres:
    image: postgres:17.4
    container_name: test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U", "test" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: