name: CI & Deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.4
        ports: [5432:5432]
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: configure poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: run tests
        env:
          DATABASE_URL: postgresql+asyncpg://test:test@postgres:5432/test
        run: |
          pytest tests/ -v --maxfail=1 --disable-warnings

      - name: deploy to vps
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ponchik/
            git stash
            git pull origin develop
            sudo make down
            sudo make up